services:
  webclaw:
    image: land007/webclaw_lite:latest
    container_name: webclaw-remote-ab32eb6fd6a34f8f9cd15cd307da0220
    privileged: true
    networks:
      - internal_network
    ports:
      - "20000:20000"
      - "15050:20000"
    devices:
      - /dev/fuse
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dna-data:/home/ubuntu/dna
      #- projects:/home/ubuntu/projects
      - vibe-kanban-data:/home/ubuntu/.local/share/vibe-kanban
      - theia-data:/home/ubuntu/.theia
      - user-data:/home/ubuntu/.local/share
      - gitconfig:/home/ubuntu/.gitconfig-vol
      - openclaw-data:/home/ubuntu/.openclaw
      - chrome-data:/home/ubuntu/.config
      - v2rayn-data:/home/ubuntu/.local/share/v2rayN
      - /home/ubuntu/docker/:/home/ubuntu/projects/docker
      - /home/ubuntu/docker_build/:/home/ubuntu/projects/docker_build
      - ./node-theia_project:/home/ubuntu/projects/project
      - ./node-theia_dub_start.sh:/start.sh
    environment:
      - MODE=lite
      - ENABLE_KANBAN=false
      - ENABLE_OPENCLAW=true
      - ENABLE_CLAUDECODEUI=false
      - AUTH_USER=admin
      - AUTH_PASSWORD=FVE4MtJBZbtec5gj
      - OPENCLAW_GATEWAY_TOKEN=xkYrN76UaVCFNoDhpUPbMNWE
      - PASSWORD=FVE4MtJBZbtec5gj
      - VNC_PASSWORD=FVE4MtJBZbtec5gj
      - VNC_RESOLUTION=1920x1080
      - CF_TUNNEL_TOKEN=
      - GIT_USER_NAME=Yiqiu Jia
      - GIT_USER_EMAIL=yiqiujia@hotmail.com
      - DNA_REPO_URL=
      - DOCKER_SOCK_MODE=host
    shm_size: "512m"
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
# docker exec -it webclaw-remote-ab32eb6fd6a34f8f9cd15cd307da0220 bash
# sudo ip route del default
# sudo ip route add default via 172.18.0.100
# cd /home/ubuntu/projects/project/dub_precedent && npm run start

volumes:
  dna-data:
  projects:
  vibe-kanban-data:
  theia-data:
  user-data:
  openclaw-data:
  chrome-data:
  v2rayn-data:
  gitconfig: