[program:cloudflared]
command=/usr/local/bin/run-cloudflared.sh
user=ubuntu
autostart=true
autorestart=unexpected
exitcodes=0,78
priority=900
stdout_logfile=/tmp/cloudflared_stdout.log
stderr_logfile=/tmp/cloudflared_stderr.log
