[program:webtty]
command=/opt/start-webtty.sh
directory=/home/ubuntu/projects
user=ubuntu
environment=HOME="/home/ubuntu",SHELL="/bin/bash",TERM="xterm-256color"
priority=220
autostart=true
autorestart=true
startretries=5
startsecs=5
stdout_logfile=/tmp/webtty_stdout.log
stderr_logfile=/tmp/webtty_stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
