[program:clipboard-server]
command=/usr/bin/node /opt/clipboard-server.js
user=ubuntu
autostart=true
autorestart=true
priority=150
stdout_logfile=/tmp/clipboard-server_stdout.log
stderr_logfile=/tmp/clipboard-server_stderr.log
environment=NODE_ENV="production"
