[program:ssh-server]
command=/opt/start-ssh.sh
directory=/home/ubuntu
user=root
environment=HOME="/root",SSH_PORT="%(ENV_SSH_PORT)s",SSH_AUTHORIZED_KEYS="%(ENV_SSH_AUTHORIZED_KEYS)s",PASSWORD="%(ENV_PASSWORD)s"
priority=150
autostart=%(ENV_ENABLE_SSH_SERVER)s
autorestart=true
startretries=3
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/tmp/ssh-server_stdout.log
stderr_logfile=/tmp/ssh-server_stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
